server:
  port: 8090


spring:
  datasource:
    url : jdbc:mysql://localhost:3306/parkingcloud?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username : root
    password : 123456

  redis:
    database: 1
    timeout: 3000
    # Redis服务器地址
    host: 10.20.1.32
    # Redis服务器连接端口
    port: 6380
    # Redis服务器连接密码（默认为空）
    password:
      # 连接池最大连接数（使用负值表示没有限制）
    pool:
      max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
        # 连接池中的最大空闲连接
      max-idle: 8
        # 连接池中的最小空闲连接
      min-idle: 0

mybatis-plus:
    mapper-locations: classpath*:mapper/**/*.xml
    global-config:
      db-config:
       id-type: auto
       field-strategy: not_empty
       #驼峰下划线转换
       column-underline: true
       #逻辑删除配置
       logic-delete-value: 0
       logic-not-delete-value: 1
       db-type: mysql
      refresh: false
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: false